# Generated by Django 2.1.2 on 2020-10-05 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDesk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobs', models.CharField(choices=[('Wishlist', 'Wishlist'), ('Email_marketing', 'Emailing')], max_length=25)),
                ('member_id', models.CharField(max_length=100)),
                ('member_name', models.CharField(max_length=30)),
                ('board', models.CharField(blank=True, choices=[('Todo', 'To Do'), ('On_Progress', 'On Progress'), ('Report', 'Report'), ('Done', 'Done')], max_length=25)),
            ],
            options={
                'verbose_name': 'Jobdesk',
                'verbose_name_plural': 'Jobsdesk',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_status', models.CharField(choices=[('Admin', 'admin'), ('Tim', 'tim')], max_length=10)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_office', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.AddField(
            model_name='jobdesk',
            name='delegation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simplycrm.Staff'),
        ),
    ]
